ALTER TABLE users
  ADD COLUMN member_status ENUM('QIU_DAO_BARU','ANGGOTA_LAMA') NOT NULL DEFAULT 'QIU_DAO_BARU' AFTER qiu_dao_card_url,
  ADD COLUMN division ENUM('BELUM_DITENTUKAN','FA_HUI_CU','THAN_WU_ALTAR','CAO_TAI_PELAYANAN','CIAO_KE_LAGU_SUCI','FAS','PELATIHAN','DATA_ANALYSIS','SUPPORT','LAINNYA') NOT NULL DEFAULT 'BELUM_DITENTUKAN' AFTER member_status;

UPDATE users
SET division = 'FA_HUI_CU'
WHERE division = 'BELUM_DITENTUKAN'
  AND status = 'ACTIVE';
